apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ig3m7cyea-go
  janus-idp.io/tekton: ig3m7cyea-go
  backstage.io/kubernetes-id: ig3m7cyea-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ig3m7cyea-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
